### PR TITLE
Detect TLD DB change

### PR DESCRIPTION
**Pull request by szepeviktor**
Composer is updated in all Travis images.

### CODE REVIEW

**Comment by szepeviktor** [comment]
plus header fix https://developer.wordpress.org/plugins/plugin-basics/header-requirements/

**Comment by szepeviktor** [comment]
Why isn't Travis showing? https://travis-ci.org/arubacao/tld-checker/builds/643060627

**Comment by szepeviktor** [comment]
All green 🍏 https://travis-ci.org/arubacao/tld-checker/builds/643065842

**Comment by arubacao** [comment]
Could you explain what exactly happens?
Will Travis fail when the DB is changed?

**Comment by szepeviktor** [comment]
>  Will Travis fail when the DB is changed?

Yes. It is regenerated and compared by `git diff --exit-code`

**Comment by arubacao** [comment]
Nice. Thanks!

**Comment by szepeviktor** [comment]
You're welcome.

**Comment by szepeviktor** [comment]
@arubacao 1 The %GENERATED% line will always differ and cause the test to fail

kép

2 Currently we need to update the DB.

3 Travis does not appear in PR-s

kép

and [GitHub Refined](https://github.com/sindresorhus/refined-github) does not detect it

kép

**Comment by arubacao** [comment]
@szepeviktor I simply removed the timestamp since the database timestamp is also mentioned in the comments.
Do you know why the travis builds are not reflected on GitHub? They are actually running on travis for PRs.

**Comment by szepeviktor** [comment]
I've noticed it also.
Haven't they moved from travis.org to travis.com?

**Comment by arubacao** [comment]
I revoked & reinstalled travis. It seems to work again: https://github.com/arubacao/tld-checker/pull/15

**Comment by arubacao** [comment]
Btw: https://github.com/arubacao/tld-checker/commit/cb91731da898c6ddbc1c11923e44cc5f7e35732c
Now it actually works as expected. Until now the version number check would just exit the script and didn't detect TLD changes. Also iana sometimes changes the version number without actual tld changes

**Pull request merged**
